[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''

[[plugins]] 
repo = 'prabirshrestha/async.vim'

[[plugins]] 
repo = 'prabirshrestha/vim-lsp'

[[plugins]] 
repo = 'mattn/vim-lsp-settings'
merged = '0'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  let g:asyncomplete_auto_popup = 1
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]] 
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
  autocmd BufRead,BufNewFile *.md  set filetype=markdown
  let g:vim_markdown_folding_disabled=1
  let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  let g:closetag_filenames = '*.html,*.vue'
'''
