[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1
'''

[[plugins]] 
repo = 'prabirshrestha/async.vim'

[[plugins]] 
repo = 'prabirshrestha/vim-lsp'

[[plugins]] 
repo = 'mattn/vim-lsp-settings'
merged = '0'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  let g:asyncomplete_auto_popup = 1
  let g:auto_save_in_insert_mode = 0
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
hook_add = '''
  nnoremap <silent> <leader>ld :LspDefinition<CR>
  nnoremap <silent> <leader>li :LspImplementation<CR>
'''

[[plugins]] 
repo = 'doums/darcula'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
  autocmd BufRead,BufNewFile *.md  set filetype=markdown
  let g:vim_markdown_folding_disabled=1
  let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  let g:closetag_filenames = '*.html,*.vue'
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'mattn/vim-lexiv'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
 
###fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap <silent> <leader>r :Rg<CR>
  nnoremap <silent> <leader>g :GFiles<CR>
'''
