[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1
'''

[[plugins]] 
repo = 'prabirshrestha/async.vim'

[[plugins]] 
repo = 'prabirshrestha/vim-lsp'

[[plugins]] 
repo = 'mattn/vim-lsp-settings'
merged = '0'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  let g:asyncomplete_auto_popup = 1
  let g:auto_save_in_insert_mode = 0
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
hook_add = '''
  nnoremap <silent> <leader>ld :LspDefinition<CR>
  nnoremap <silent> <leader>li :LspImplementation<CR>
  nnoremap <silent> <leader>lr :LspRename<CR>
  nnoremap <silent> <leader>lc :LspCodeAction<CR>
'''

[[plugins]] 
repo = 'ulwlu/elly.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
  autocmd BufRead,BufNewFile *.md  set filetype=markdown
  let g:vim_markdown_folding_disabled=1
  let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  let g:closetag_filenames = '*.html,*.vue'
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'mattn/vim-lexiv'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
 
###fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap <silent> <leader>r :Rg<CR>
  nnoremap <silent> <leader>g :GFiles<CR>
'''

[[plugins]]
repo = 'vim-test/vim-test'
hook_add = '''
  nmap <silent> t<C-n> :TestNearest<CR>
  nmap <silent> t<C-f> :TestFile<CR>
  nmap <silent> t<C-s> :TestSuite<CR>
  nmap <silent> t<C-l> :TestLast<CR>
  nmap <silent> t<C-g> :TestVisit<CR>
'''

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsExpandTrigger="<tab>"
  let g:UltiSnipsJumpForwardTrigger="<c-j>"
  let g:UltiSnipsJumpBackwardTrigger="<c-k>"
  nnoremap <silent> <leader>s :Snippets<CR>
'''

[[plugins]]
repo = 'honza/vim-snippets'

# go get github.com/go-delve/delve/cmd/dlv
[[plugins]]
repo = 'sebdah/vim-delve'
hook_add = '''
  nnoremap <silent> <leader>d :DlvDebug<CR>
  nnoremap <silent> <leader>b :DlvToggleBreakpoint<CR>
'''

[[plugins]]
repo = 'buoto/gotests-vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  let g:fern#default_hidden=1
  nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''
